In [1]:
import os
print(os.getcwd())
print(os.listdir())

/Users/bayoadeyanju/Desktop/Data Science
['Untitled1.ipynb', '.DS_Store', 'Untitled.ipynb', 'Feature Engineering & ML Pipeline Basics.pptx', 'week 4 Assignmnet', '.ipynb_checkpoints']

In [2]:
import pandas as pd

df = pd.read_csv("week 4 Assignment/brasil-real-estate-1.csv", encoding="latin1")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'week 4 Assignment/brasil-real-estate-1.csv'

In [3]:
import pandas as pd

df = pd.read_csv("brasil-real-estate-1.csv", encoding="latin1")
df.head()

,Unnamed: 0,property_type,place_with_parent_names,region,lat-lon,area_m2,price_usd
0,1,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.6443051,-35.7088142",110,"$187,230.85"
1,2,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.6430934,-35.70484",65,"$81,133.37"
2,3,house,|Brasil|Alagoas|Maceió|,Northeast,"-9.6227033,-35.7297953",211,"$154,465.45"
3,4,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.622837,-35.719556",99,"$146,013.20"
4,5,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.654955,-35.700227",55,"$101,416.71"

In [4]:
df.head()

,Unnamed: 0,property_type,place_with_parent_names,region,lat-lon,area_m2,price_usd
0,1,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.6443051,-35.7088142",110,"$187,230.85"
1,2,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.6430934,-35.70484",65,"$81,133.37"
2,3,house,|Brasil|Alagoas|Maceió|,Northeast,"-9.6227033,-35.7297953",211,"$154,465.45"
3,4,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.622837,-35.719556",99,"$146,013.20"
4,5,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.654955,-35.700227",55,"$101,416.71"

In [5]:
df.shape

(12834, 7)

In [6]:
df.columns

Index(['Unnamed: 0', 'property_type', 'place_with_parent_names', 'region',
       'lat-lon', 'area_m2', 'price_usd'],
      dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12834 entries, 0 to 12833
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               12834 non-null  int64
 1   property_type            12834 non-null  str
 2   place_with_parent_names  12834 non-null  str
 3   region                   12834 non-null  str
 4   lat-lon                  11551 non-null  str
 5   area_m2                  12834 non-null  int64
 6   price_usd                12834 non-null  str
dtypes: int64(2), str(5)
memory usage: 1.7 MB

In [8]:
df.describe()

         Unnamed: 0       area_m2
count  12834.000000  12834.000000
mean    6417.500000    116.687003
std     3705.001012     48.260754
min        1.000000     53.000000
25%     3209.250000     78.000000
50%     6417.500000    105.000000
75%     9625.750000    145.000000
max    12834.000000    252.000000

In [9]:
print(df.head())

print(df.info())

   Unnamed: 0 property_type  place_with_parent_names     region  \
0           1     apartment  |Brasil|Alagoas|Maceió|  Northeast
1           2     apartment  |Brasil|Alagoas|Maceió|  Northeast
2           3         house  |Brasil|Alagoas|Maceió|  Northeast
3           4     apartment  |Brasil|Alagoas|Maceió|  Northeast
4           5     apartment  |Brasil|Alagoas|Maceió|  Northeast

                  lat-lon  area_m2    price_usd
0  -9.6443051,-35.7088142      110  $187,230.85
1    -9.6430934,-35.70484       65   $81,133.37
2  -9.6227033,-35.7297953      211  $154,465.45
3    -9.622837,-35.719556       99  $146,013.20
4    -9.654955,-35.700227       55  $101,416.71
<class 'pandas.DataFrame'>
RangeIndex: 12834 entries, 0 to 12833
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               12834 non-null  int64
 1   property_type            12834 non-null  str
 2   place_with_parent_names  12834 non-null  str
 3   region                   12834 non-null  str
 4   lat-lon                  11551 non-null  str
 5   area_m2                  12834 non-null  int64
 6   price_usd                12834 non-null  str
dtypes: int64(2), str(5)
memory usage: 1.7 MB
None

In [10]:
df[['empty1', 'country', 'state', 'city', 'empty2']] = \
    df['place_with_parent_names'].str.split('|', expand=True)

df = df.drop(columns=['place_with_parent_names', 'empty1', 'empty2'])

ValueError: Columns must be same length as key

In [11]:
df['place_with_parent_names'].str.split('|', expand=True)

      0        1           2       3           4    5
0         Brasil     Alagoas  Maceió              NaN
1         Brasil     Alagoas  Maceió              NaN
2         Brasil     Alagoas  Maceió              NaN
3         Brasil     Alagoas  Maceió              NaN
4         Brasil     Alagoas  Maceió              NaN
...   ..     ...         ...     ...         ...  ...
12829     Brasil  Pernambuco  Recife              NaN
12830     Brasil  Pernambuco  Recife              NaN
12831     Brasil  Pernambuco  Recife  Boa Viagem
12832     Brasil  Pernambuco  Recife  Boa Viagem
12833     Brasil  Pernambuco  Recife  Boa Viagem

[12834 rows x 6 columns]

In [13]:
df[['empty1', 'country', 'state', 'city', 'empty2', 'empty3']] = (
    df['place_with_parent_names'].str.split('|', expand=True)
)

In [14]:
df = df.drop(columns=['place_with_parent_names', 'empty1', 'empty2', 'empty3'])

In [15]:
df.head()

,Unnamed: 0,property_type,region,lat-lon,area_m2,price_usd,country,state,city
0,1,apartment,Northeast,"-9.6443051,-35.7088142",110,"$187,230.85",Brasil,Alagoas,Maceió
1,2,apartment,Northeast,"-9.6430934,-35.70484",65,"$81,133.37",Brasil,Alagoas,Maceió
2,3,house,Northeast,"-9.6227033,-35.7297953",211,"$154,465.45",Brasil,Alagoas,Maceió
3,4,apartment,Northeast,"-9.622837,-35.719556",99,"$146,013.20",Brasil,Alagoas,Maceió
4,5,apartment,Northeast,"-9.654955,-35.700227",55,"$101,416.71",Brasil,Alagoas,Maceió

In [17]:
df[['lat', 'lon']] = df['lat-lon'].str.split(',', expand=True)

df['lat'] = df['lat'].astype(float)
df['lon'] = df['lon'].astype(float)

df = df.drop(columns=['lat-lon'])

df.head()

,Unnamed: 0,property_type,region,area_m2,price_usd,country,state,city,lat,lon
0,1,apartment,Northeast,110,"$187,230.85",Brasil,Alagoas,Maceió,-9.644305,-35.708814
1,2,apartment,Northeast,65,"$81,133.37",Brasil,Alagoas,Maceió,-9.643093,-35.704840
2,3,house,Northeast,211,"$154,465.45",Brasil,Alagoas,Maceió,-9.622703,-35.729795
3,4,apartment,Northeast,99,"$146,013.20",Brasil,Alagoas,Maceió,-9.622837,-35.719556
4,5,apartment,Northeast,55,"$101,416.71",Brasil,Alagoas,Maceió,-9.654955,-35.700227

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12834 entries, 0 to 12833
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     12834 non-null  int64
 1   property_type  12834 non-null  str
 2   region         12834 non-null  str
 3   area_m2        12834 non-null  int64
 4   price_usd      12834 non-null  str
 5   country        12834 non-null  str
 6   state          12834 non-null  str
 7   city           12834 non-null  str
 8   lat            11551 non-null  float64
 9   lon            11551 non-null  float64
dtypes: float64(2), int64(2), str(6)
memory usage: 1.6 MB

In [19]:
df.isnull().sum()

Unnamed: 0          0
property_type       0
region              0
area_m2             0
price_usd           0
country             0
state               0
city                0
lat              1283
lon              1283
dtype: int64

In [20]:
df = df.dropna()

df.info()

df.isnull().sum()

<class 'pandas.DataFrame'>
Index: 11551 entries, 0 to 12833
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     11551 non-null  int64
 1   property_type  11551 non-null  str
 2   region         11551 non-null  str
 3   area_m2        11551 non-null  int64
 4   price_usd      11551 non-null  str
 5   country        11551 non-null  str
 6   state          11551 non-null  str
 7   city           11551 non-null  str
 8   lat            11551 non-null  float64
 9   lon            11551 non-null  float64
dtypes: float64(2), int64(2), str(6)
memory usage: 1.6 MB

Unnamed: 0       0
property_type    0
region           0
area_m2          0
price_usd        0
country          0
state            0
city             0
lat              0
lon              0
dtype: int64

In [21]:
X = df.drop(columns=["price_usd"])
y = df["price_usd"]

print(X.head())
print(y.head())

   Unnamed: 0 property_type     region  area_m2 country    state    city  \
0           1     apartment  Northeast      110  Brasil  Alagoas  Maceió
1           2     apartment  Northeast       65  Brasil  Alagoas  Maceió
2           3         house  Northeast      211  Brasil  Alagoas  Maceió
3           4     apartment  Northeast       99  Brasil  Alagoas  Maceió
4           5     apartment  Northeast       55  Brasil  Alagoas  Maceió

        lat        lon
0 -9.644305 -35.708814
1 -9.643093 -35.704840
2 -9.622703 -35.729795
3 -9.622837 -35.719556
4 -9.654955 -35.700227
0    $187,230.85
1     $81,133.37
2    $154,465.45
3    $146,013.20
4    $101,416.71
Name: price_usd, dtype: str

In [22]:
print(X.shape)
print(y.shape)

(11551, 9)
(11551,)

In [23]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(9240, 9)
(2311, 9)
(9240,)
(2311,)

In [24]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

ValueError: could not convert string to float: 'apartment'

In [25]:
X = pd.get_dummies(X, drop_first=True)

print(X.head())
print(X.shape)

   Unnamed: 0  area_m2       lat        lon  property_type_house  \
0           1      110 -9.644305 -35.708814                False
1           2       65 -9.643093 -35.704840                False
2           3      211 -9.622703 -35.729795                 True
3           4       99 -9.622837 -35.719556                False
4           5       55 -9.654955 -35.700227                False

   region_North  region_Northeast  region_South  region_Southeast  \
0         False              True         False             False
1         False              True         False             False
2         False              True         False             False
3         False              True         False             False
4         False              True         False             False

   state_Amapá  ...  city_Três Lagoas  city_Uberaba  city_Uberlândia  \
0        False  ...             False         False            False
1        False  ...             False         False            False
2        False  ...             False         False            False
3        False  ...             False         False            False
4        False  ...             False         False            False

   city_Vianópolis  city_Vila Boa  city_Vila Velha  city_Vitória  \
0            False          False            False         False
1            False          False            False         False
2            False          False            False         False
3            False          False            False         False
4            False          False            False         False

   city_Vitória da Conquista  city_Várzea Grande  city_Águas Claras
0                      False               False              False
1                      False               False              False
2                      False               False              False
3                      False               False              False
4                      False               False              False

[5 rows x 135 columns]
(11551, 135)

In [26]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [27]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

ValueError: could not convert string to float: '$106,097.48'

In [28]:
print(y.dtype)
y.head()

str

0    $187,230.85
1     $81,133.37
2    $154,465.45
3    $146,013.20
4    $101,416.71
Name: price_usd, dtype: str

In [29]:
y = (
    y.replace(r'[\$,]', '', regex=True)
     .astype(float)
)

In [30]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [31]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [32]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

y_pred = model.predict(X_test)

print("R² Score:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", mean_squared_error(y_test, y_pred) ** 0.5)

R² Score: 0.5365509523514854
MAE: 49196.540358877566
RMSE: 67986.52877482052

In [33]:
results = pd.DataFrame({
    "Actual": y_test,
    "Predicted": y_pred
})

results.head(10)

          Actual      Predicted
5510   104160.09  119800.788346
6558   151344.94  171043.822395
1081   378763.96  247708.951956
6000   148224.42  129463.776774
12818  390064.28  395300.744432
1248   149784.68  139768.040189
8591    93615.42  141537.700907
5184   106097.48  114418.475276
10022  142036.48  195321.309568
4880   102040.81   94876.777867

In [34]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

# Numeric and categorical features
numeric_features = ['area_m2', 'lat', 'lon']
categorical_features = ['property_type', 'country', 'state', 'city']

# Numeric pipeline
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

# Categorical pipeline
categorical_transformer = Pipeline(steps=[
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

# Combine both pipelines
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ]
)

# Transform the training data
X_train_processed = preprocessor.fit_transform(X_train)

print("Original Training Data Shape:", X_train.shape)
print("Processed Training Data Shape:", X_train_processed.shape)
print("Pipeline completed successfully!")

ValueError: Some column names are not columns of the dataframe: {'city', 'country', 'property_type', 'state'}

In [35]:
print(df.columns.tolist())

['Unnamed: 0', 'property_type', 'region', 'area_m2', 'price_usd', 'country', 'state', 'city', 'lat', 'lon']

In [36]:
X = df.drop(columns=["price_usd"])
y = df["price_usd"]

In [37]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [38]:
X_train_processed = preprocessor.fit_transform(X_train)

In [39]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

# Numeric and categorical features
numeric_features = ['area_m2', 'lat', 'lon']
categorical_features = ['property_type', 'country', 'state', 'city']

# Numeric pipeline
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

# Categorical pipeline
categorical_transformer = Pipeline(steps=[
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

# Combine both pipelines
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ]
)

# Transform the training data
X_train_processed = preprocessor.fit_transform(X_train)

print("Original Training Data Shape:", X_train.shape)
print("Processed Training Data Shape:", X_train_processed.shape)
print("Pipeline completed successfully!")

Original Training Data Shape: (9240, 9)
Processed Training Data Shape: (9240, 127)
Pipeline completed successfully!

In [40]:
print(X_train_processed.shape)

(9240, 127)